### PR TITLE
Update most-recent after transition destroy

### PR DESCRIPTION
**Pull request by greysteil**
This is a good pattern suggested in #179. Just affects the ActiveRecord transition model generator.

### CODE REVIEW

**Comment by isaacseymour** [comment]
:+1:

**Comment by hale** [comment]
Thanks for adding this.  What about `after_destroy :update_most_recent, if: :most_recent?`, so we only update when necessary?

**Comment by greysteil** [comment]
We're about to 2.0 statesman to make the `most_recent` column required - see https://github.com/gocardless/statesman/pull/184. This change will go out in that version, so I think we're fine here.

**Comment by hale** [comment]
I was more thinking that we only care about updating the `most_recent` column if the deleted transition is the most recent - otherwise, we can skip the callback.

With the condition the `most_recent` column is checked after every destroy. Without it,  every destroy sorts the table then checks the `most_recent` column to see if it needs to `UPDATE`. 

Maybe this doesn't matter in practice.

**Comment by greysteil** [comment]
Good shout. Done in https://github.com/gocardless/statesman/commit/926f45417f59a76af9fc3f143c657f3cde0cdcc1.

**Pull request merged**
