### PR TITLE
Run tests against edgy Rails

### PR DESCRIPTION
**Pull request by isaacseymour**
- use 6.0.0.rc1, rather than 6.0.0.beta3
- also run tests against latest master of Rails (currently 6.1)
- define renamed method `trigger_transactional_callbacks?` required by 6.1 (see https://github.com/st0012/rails/commit/01f8abd7b2e46aa61eb60a96c456d67364948b24)

### CODE REVIEW

**Comment by lawrencejones** [comment]
It's worth calling out https://github.com/gocardless/statesman/pull/351 which would be relevant to this work. @isaacseymour let me know when you're finished breaking tests and I'll get to a review ;)

**Comment by isaacseymour** [comment]
Ohh good point. Yep I'm done with breaking tests - I think the ones which are still broken are unrelated to 6.1, but break in 6.0 as well.

**Comment by lawrencejones** [comment]
Hey @isaacseymour, I think these changes are still nice tidy-ups but will need rebasing against https://github.com/gocardless/statesman/pull/355

Do you want to do that then we can figure out which test failures are false positives/things we don't care about?

**Comment by isaacseymour** [comment]
Rebased - seems like there's still that issue with mongo + sqlite3 + rails 6 🤔 v strange

**Comment by isaacseymour** [comment]
Ok I think the issue is that [mongoid][1]

**Pull request merged**
