### PR TITLE
Arthurnn/deadlocks

### PR DESCRIPTION
**Pull request by greysteil**
Adds a commit to https://github.com/gocardless/statesman/pull/350 (I'm not a maintainer, so couldn't do it from within that PR).

### CODE REVIEW

**Comment by greysteil** [comment]
@lawrencejones my first commit fixes the `.or(` problems, but it looks like this PR has two additional problems:
- Getting type casting right when using a `case` statement is tricky for older combinations of Rails and postgres.
- We seem to be failing a uniqueness constraint on MySQL, even when the type casting works. See [this failure](https://circleci.com/gh/gocardless/statesman/7470?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for an example.

I'm sure the first issue is solvable. I'm a little more concerned about the later.

I'm not going to have more time to work on this - writing code isn't officially part of my job at GitHub and I'm not well placed to debug things further here :-(

**Comment by lawrencejones** [comment]
Totally understand. I am Keen to give this time, just oversubscribed for this week, and I'd imagine all GC engineers are too. Will give a call round and see if anyone has some free time but otherwise next Monday is the most likely time to get back to this. 

Also, this PR was useful regardless. And who knows, by next week maybe rails 6 will be officially released and we can forget about senile rails versions!

**Comment by lawrencejones** [comment]
Hey @greysteil, pretty sure I have a fix for this. 

Can you give me write permission on your fork for the time being? I cba creating yet another PR haha

**Comment by greysteil** [comment]
Yep - you should have it!

**Comment by lawrencejones** [comment]
Ok! So what is currently in this PR will resolve the problems we were seeing.

Unfortunately it breaks many a test. However the failures should be exclusively on Rails 4, which we intend to deprecate as soon as Rails 6 is fully released, so I don't think this is a big deal.

The biggest piece of work required around this change is performance testing. If we deploy this and verify the performance is unchanged/improved, we can go ahead and merge to master in anticipation of the Rails 6 release and get this out in the wild.

I'm going to ping the GC Banking teams to ask them to trial this branch to confirm no performance regressions. Hopefully we'll have an answer by EoW and can make a decision.

**Comment by lawrencejones** [comment]
Checking in on this: payments-service has some test failures that I've not yet had time to look into. Rounded up some volunteers (big-up @thom-oman!) from our Banking teams to double check the performance though, so this should be quite quick provided I can find some space to fix-up the tests.

**Comment by jurre** [comment]
Hi @lawrencejones, we're currently running into these deadlocks at GitHub, would it help if I carve out some time this week to fix up the tests?

**Comment by thom-oman** [comment]
Hey @jurre sorry for the delays on this, both me and Lawrence haven't been able to devote any time to work on this. I managed to get all tests passing on a branch of mine last September but if I recall correctly there was some clean up to do, as well making sure this doesn't cause any performance regressions.

I will spend some time later today seeing what needs to be done but unfortunately I won't be able to dedicate much time to it until next week.

**Comment by jurre** [comment]
Thanks @thom-oman! Please let me know if there's anything I can do to help ❤️

**Comment by thom-oman** [comment]
Quick update, good news is that I think we're very close. All tests were already passing, minus some PG related failures, those should be fixed in https://github.com/gocardless/statesman/pull/398. 

I've opened (yet another) PR [here](https://github.com/gocardless/statesman/pull/399), will try to get some more GC eyes on it as soon as we can, would appreciate any comments from your side too. Hopefully we can get that merged pretty soon and finally get this issue resolved 😅

**Comment by thom-oman** [comment]
Today I'm going to see if it breaks anything in our monolith, but besides that, we should be good to merge pretty soon 👍

**Comment by jurre** [comment]
Awesome, thanks so much @thom-oman 🥇

**Comment by lawrencejones** [comment]
Superseded by #399. Thanks all for the help, and sorry for the (very large) delay.

**Pull request closed without merging**
