### PR TITLE
Use mongoid 5.0

### PR DESCRIPTION
**Pull request by petehamilton**
@hmarr mongoid stopped using Moped and since we have version `>= 3` specified in the gemspec, it's causing Travis builds to fail.

Changelog: https://github.com/mongodb/mongoid/blob/master/CHANGELOG.md#major-changes-backwards-incompatible

@greysteil FYI

### CODE REVIEW

**Comment by petehamilton** [comment]
Turns out this then has a conflict in activemodel...

```
  In Gemfile:
    mongoid (>= 5.0) ruby depends on
      activemodel (~> 4.0) ruby
    rails (~> 3.2.21) ruby depends on
      activeresource (= 3.2.21) ruby depends on
        activemodel (3.2.21)
```

So I've bumped rails to `>= 4.0` as well to see what the knock-on is. Will play later and see if I can drop them back down.,

**Comment by greysteil** [comment]
I'm happy to EoL Rails 3.2 as part of Statesman 2.0.

http://stackoverflow.com/questions/27618185/when-does-rails-3-2-reach-end-of-life

**Comment by hmarr** [comment]
:+1:

**Comment by greysteil** [comment]
:+1:

**Pull request merged**
