### PR TITLE
Optimize MySQL indexes for transition model

### PR DESCRIPTION
**Pull request by mkdynamic**
See https://github.com/gocardless/statesman/issues/59 for more details.

### CODE REVIEW

**Comment by greysteil** [comment]
Looks good to me. @hmarr / @alan / @Sinjo - can one of you sign off?

http://dev.mysql.com/doc/refman/5.0/en/multiple-column-indexes.html
http://www.postgresql.org/docs/9.0/static/indexes-multicolumn.html

**Comment by Sinjo** [comment]
This makes sense. I can't imagine a case where you'd use the `sort_key` in a way that isn't scoped to a specific parent, so there's no advantage to `[:sort_key, :parent_id]` over `[:parent_id, :sort_key]`.

When you're only looking up by the `parent_id`, Postgres will happily use the first column of the index (and I believe the same holds in other databases).

**Comment by greysteil** [comment]
@mkdynamic - thanks for this, and apologies for the delay getting it merged!

**Comment by mkdynamic** [comment]
No worries. Thanks!

**Pull request merged**
