### PR TITLE
Drop support for Mongo

### PR DESCRIPTION
**Pull request by josephfrazier**
Fixes https://github.com/gocardless/statesman/issues/266

### CODE REVIEW

**Comment by lawrencejones** [comment]
Haha you're on fire @josephfrazier! Really cool that you were so proactive.

Two things:

1. We should hold off from merging this until we decide a release plan. The best place to discuss this will be in #266 
2. In anticipation of merging this, can I ask that you squash your commits and provide a commit message that helps people understand why this happened? An example of a good commit message would be [this](https://github.com/gocardless/statesman/commit/0a2ed0327857ac3df612eb79bf24c937383368ce). Let me know if I can help!

**Comment by lawrencejones** [comment]
Hey @josephfrazier- can you fixup your conflicts and then squash the commits into a single change?

Then we can get this merged.

**Comment by lawrencejones** [comment]
Gentle poke on this @josephfrazier - would love to get this merged.

**Comment by josephfrazier** [comment]
Just resolved the merge conflicts, I believe. Do you have a particular commit message in mind? If so, you should be able to use github's "Squash and merge" option to land this as a single commit with the desired message.

**Comment by lawrencejones** [comment]
Hadn't noticed you could reword the message there- thanks for the tip, and the PR!

**Comment by josephfrazier** [comment]
Cool, thanks for the merge!

**Pull request merged**
