### PR TITLE
Add Rails 5 to Travis.yml

### PR DESCRIPTION
**Pull request by greysteil**
That. Pending adding support to Mongoid, which is pending a release for https://github.com/rails/activemodel-serializers-xml.

See https://github.com/rails/activemodel-serializers-xml/issues/5 for updates.

### CODE REVIEW

**Comment by rthbound** [comment]
@greysteil : We now have beta2 and beta3, in case you'd like to update this PR.

**Comment by greysteil** [comment]
Thanks @rthbound. Still waiting on Mongoid support, which is pending https://github.com/mongodb/mongoid/pull/4234.

**Comment by greysteil** [comment]
@petehamilton - can you review? Some brave individuals are using Rails 5 in the wild, so we should support them...!

**Comment by petehamilton** [comment]
:+1:

**Pull request merged**
